version: '3.7'

services:
  auth_api:
    container_name: auth_api
    env_file:
      - ./auth_api/cmd/auth_api/.env
    build:
      context: ./auth_api/.
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    expose:
      - 8080
    depends_on:
      - auth_api_mysql
      - auth_api_redis
  
  auth_api_redis:
    container_name: auth_api_redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    expose:
      - 6379

  auth_api_mysql:
    container_name: auth_api_mysql
    image: mysql:8.4.0
    volumes:
      - ./auth_api/scripts/sql/:/docker-entrypoint-initdb.d/
      - auth_api_mysql_data:/var/lib/mysql
    env_file:
      - ./auth_api/cmd/auth_api/.env
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  auth_api_mysql_data:
    driver: "local"